In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [3]:
air = pd.read_csv('AirQualityUCI.csv')

In [4]:
air.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10-03-2004,18:00:00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,NaN,NaN
1,10-03-2004,19:00:00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,NaN,NaN
2,10-03-2004,20:00:00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,NaN,NaN
3,10-03-2004,21:00:00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,NaN,NaN
4,10-03-2004,22:00:00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,NaN,NaN

In [5]:
air.tail()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
9466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
air.shape

(9471, 17)

In [7]:
air.isnull()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
27,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9441,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9442,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9443,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9444,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9445,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9446,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9447,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9448,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9449,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9450,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9451,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9452,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9453,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9454,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9455,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9456,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9457,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9458,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9459,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9460,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9461,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9462,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9463,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9464,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9465,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9466,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9467,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9468,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9469,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
9470,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [8]:
#data cleaning
air.fillna(air.mode().iloc[0],inplace=True)

In [9]:
air.describe()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
count,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,9471.000000,0.0,0.0
mean,-36.203125,1033.956288,-159.582515,-0.564122,881.419913,164.180023,783.013726,55.041601,1372.323408,960.927991,7.253257,36.602756,-9.162650,NaN,NaN
std,79.277658,355.011244,139.016763,46.651368,360.597975,259.018201,337.943779,129.276708,495.762597,471.912072,48.656583,57.215605,44.098134,NaN,NaN
min,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,NaN,NaN
25%,0.600000,915.000000,-200.000000,3.900000,704.000000,47.000000,631.000000,51.000000,1171.000000,689.000000,10.700000,33.500000,0.676800,NaN,NaN
50%,1.500000,1050.000000,-200.000000,7.800000,890.000000,139.000000,791.000000,95.000000,1440.000000,936.000000,17.000000,48.100000,0.971100,NaN,NaN
75%,2.600000,1218.000000,-200.000000,13.500000,1102.000000,281.500000,957.000000,132.000000,1658.000000,1250.000000,24.000000,61.700000,1.291500,NaN,NaN
max,11.900000,2040.000000,1189.000000,63.700000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000,44.600000,88.700000,2.231000,NaN,NaN

In [10]:
air.drop_duplicates(inplace=True)

In [11]:
air.shape

(9358, 17)

In [12]:
#data integration
air.columns

Index(['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)',
       'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)',
       'PT08.S5(O3)', 'T', 'RH', 'AH', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [13]:
df1 = air[['CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)']]
df2 = air[['C6H6(GT)','PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)']]
df1,df2

(      CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)
 0        2.6       1360.0     150.0      11.9
 1        2.0       1292.0     112.0       9.4
 2        2.2       1402.0      88.0       9.0
 3        2.2       1376.0      80.0       9.2
 4        1.6       1272.0      51.0       6.5
 5        1.2       1197.0      38.0       4.7
 6        1.2       1185.0      31.0       3.6
 7        1.0       1136.0      31.0       3.3
 8        0.9       1094.0      24.0       2.3
 9        0.6       1010.0      19.0       1.7
 10    -200.0       1011.0      14.0       1.3
 11       0.7       1066.0       8.0       1.1
 12       0.7       1052.0      16.0       1.6
 13       1.1       1144.0      29.0       3.2
 14       2.0       1333.0      64.0       8.0
 15       2.2       1351.0      87.0       9.5
 16       1.7       1233.0      77.0       6.3
 17       1.5       1179.0      43.0       5.0
 18       1.6       1236.0      61.0       5.2
 19       1.9       1286.0      63.0       7.3
 20       2.9       1371.0     164.0      11.5
 21       2.2       1310.0      79.0       8.8
 22       2.2       1292.0      95.0       8.3
 23       2.9       1383.0     150.0      11.2
 24       4.8       1581.0     307.0      20.8
 25       6.9       1776.0     461.0      27.4
 26       6.1       1640.0     401.0      24.0
 27       3.9       1313.0     197.0      12.8
 28       1.5        965.0      61.0       4.7
 29       1.0        913.0      26.0       2.6
 ...      ...          ...       ...       ...
 9328     1.4        970.0    -200.0       3.4
 9329     1.3       1000.0    -200.0       5.3
 9330     1.4        996.0    -200.0       5.3
 9331     1.0        928.0    -200.0       3.8
 9332     1.0        933.0    -200.0       4.2
 9333     1.1        956.0    -200.0       5.4
 9334     1.3        968.0    -200.0       6.3
 9335     1.4        953.0    -200.0       6.1
 9336     1.2       1015.0    -200.0       4.6
 9337     2.7       1248.0    -200.0      11.1
 9338     2.5       1180.0    -200.0       7.9
 9339     1.5       1102.0    -200.0       6.0
 9340     1.6       1116.0    -200.0       5.8
 9341     1.2       1100.0    -200.0       5.1
 9342     0.9       1012.0    -200.0       3.5
 9343     0.6        944.0    -200.0       1.9
 9344     0.5        912.0    -200.0       1.5
 9345     0.4        887.0    -200.0       1.1
 9346  -200.0        864.0    -200.0       0.8
 9347     0.5        888.0    -200.0       1.3
 9348     1.1       1031.0    -200.0       4.4
 9349     4.0       1384.0    -200.0      17.4
 9350     5.0       1446.0    -200.0      22.4
 9351     3.9       1297.0    -200.0      13.6
 9352     3.1       1314.0    -200.0      13.5
 9353     2.4       1163.0    -200.0      11.4
 9354     2.4       1142.0    -200.0      12.4
 9355     2.1       1003.0    -200.0       9.5
 9356     2.2       1071.0    -200.0      11.9
 9357  -200.0       -200.0    -200.0    -200.0

 [9358 rows x 4 columns],
       C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)
 0         11.9         1046.0    166.0        1056.0
 1          9.4          955.0    103.0        1174.0
 2          9.0          939.0    131.0        1140.0
 3          9.2          948.0    172.0        1092.0
 4          6.5          836.0    131.0        1205.0
 5          4.7          750.0     89.0        1337.0
 6          3.6          690.0     62.0        1462.0
 7          3.3          672.0     62.0        1453.0
 8          2.3          609.0     45.0        1579.0
 9          1.7          561.0   -200.0        1705.0
 10         1.3          527.0     21.0        1818.0
 11         1.1          512.0     16.0        1918.0
 12         1.6          553.0     34.0        1738.0
 13         3.2          667.0     98.0        1490.0
 14         8.0          900.0    174.0        1136.0
 15         9.5          960.0    129.0        1079.0
 16         6.3          827.0    112.0        1218.0
 17         5.0          762.0     95.0        1328.0
 18         5.2          774.0    104.0        1301.0
 19         7.3          869.0    146.0        1162.0
 20        11.5         1034.0    207.0         983.0
 21         8.8          933.0    184.0        1082.0
 22         8.3          912.0    193.0        1103.0
 23        11.2         1020.0    243.0        1008.0
 24        20.8         1319.0    281.0         799.0
 25        27.4         1488.0    383.0         702.0
 26        24.0         1404.0    351.0         743.0
 27        12.8         1076.0    240.0         957.0
 28         4.7          749.0     94.0        1325.0
 29         2.6          629.0     47.0        1565.0
 ...        ...            ...      ...           ...
 9328       3.4          677.0    166.0         888.0
 9329       5.3          779.0    171.0         805.0
 9330       5.3          781.0    177.0         806.0
 9331       3.8          701.0    119.0         926.0
 9332       4.2          722.0    121.0         899.0
 9333       5.4          783.0    142.0         857.0
 9334       6.3          826.0    197.0         867.0
 9335       6.1          817.0    242.0         872.0
 9336       4.6          743.0    190.0         851.0
 9337      11.1         1018.0    367.0         599.0
 9338       7.9          894.0    355.0         636.0
 9339       6.0          812.0    235.0         693.0
 9340       5.8          803.0    233.0         696.0
 9341       5.1          769.0    170.0         722.0
 9342       3.5          683.0    117.0         801.0
 9343       1.9          579.0     70.0         925.0
 9344       1.5          544.0     69.0         959.0
 9345       1.1          508.0     62.0        1047.0
 9346       0.8          478.0     52.0        1116.0
 9347       1.3          528.0     77.0        1077.0
 9348       4.4          730.0    182.0         760.0
 9349      17.4         1221.0    594.0         470.0
 9350      22.4         1362.0    586.0         415.0
 9351      13.6         1102.0    523.0         507.0
 9352      13.5         1101.0    472.0         539.0
 9353      11.4         1027.0    353.0         604.0
 9354      12.4         1063.0    293.0         603.0
 9355       9.5          961.0    235.0         702.0
 9356      11.9         1047.0    265.0         654.0
 9357    -200.0         -200.0   -200.0        -200.0

 [9358 rows x 4 columns])

In [14]:
data=pd.merge(df1,df2,on='C6H6(GT)',how='inner')
data.head(10)

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx)
0,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0
1,2.6,1360.0,150.0,11.9,1045.0,174.0,880.0
2,2.6,1360.0,150.0,11.9,1045.0,170.0,974.0
3,2.6,1360.0,150.0,11.9,1047.0,129.0,815.0
4,2.6,1360.0,150.0,11.9,1046.0,-200.0,882.0
5,2.6,1360.0,150.0,11.9,1047.0,144.0,809.0
6,2.6,1360.0,150.0,11.9,1048.0,-200.0,1016.0
7,2.6,1360.0,150.0,11.9,1046.0,177.0,838.0
8,2.6,1360.0,150.0,11.9,1046.0,146.0,777.0
9,2.6,1360.0,150.0,11.9,1045.0,207.0,761.0

In [15]:
#data transformation
air = air.astype(str)

In [16]:
encoder= LabelEncoder()
for col in air.select_dtypes(include=['object']):
    air[col]=encoder.fit_transform(air[col])

In [17]:
air.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,114,18,30,361,55,39,47,142,57,15,691,269,66,375,1896,0,0
1,114,19,24,293,17,402,1201,16,175,276,558,1716,63,363,1727,0,0
2,114,20,26,403,414,398,1185,98,141,16,554,75,49,426,1853,0,0
3,114,21,26,377,396,400,1194,149,93,25,583,204,40,486,2056,0,0
4,114,22,16,273,298,372,1082,98,205,18,489,111,42,482,2066,0,0

In [18]:
#data modeling
x = air.drop(columns=['Date','Time'])
y = air['CO(GT)']
y=y.round().astype(int)

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [20]:
model = RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [23]:
model = RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [22]:
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

0.6426282051282052