In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [3]:
heart = pd.read_csv('heart.csv')

In [4]:
heart.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [6]:
heart.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [7]:
heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
age         1025 non-null int64
sex         1025 non-null int64
cp          1025 non-null int64
trestbps    1025 non-null int64
chol        1025 non-null int64
fbs         1025 non-null int64
restecg     1025 non-null int64
thalach     1025 non-null int64
exang       1025 non-null int64
oldpeak     1025 non-null float64
slope       1025 non-null int64
ca          1025 non-null int64
thal        1025 non-null int64
target      1025 non-null int64
dtypes: float64(1), int64(13)
memory usage: 112.1 KB

In [20]:
heart.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [13]:
heart.shape

(1025, 14)

In [14]:
heart.fillna(heart.mode().iloc[0], inplace=True)

In [17]:
heart.drop_duplicates(inplace=True)

In [19]:
heart.shape

(302, 14)

In [21]:
print("Data Cleaning Done")

Data Cleaning Done

In [23]:
heart.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [24]:
df1 = heart[['age', 'sex', 'cp', 'trestbps']]
df2 = heart[['trestbps', 'chol', 'fbs', 'restecg']]

In [25]:
df1,df2

(     age  sex  cp  trestbps
 0     52    1   0       125
 1     53    1   0       140
 2     70    1   0       145
 3     61    1   0       148
 4     62    0   0       138
 5     58    0   0       100
 6     58    1   0       114
 7     55    1   0       160
 8     46    1   0       120
 9     54    1   0       122
 10    71    0   0       112
 11    43    0   0       132
 12    34    0   1       118
 13    51    1   0       140
 14    52    1   0       128
 16    51    0   2       140
 17    54    1   0       124
 18    50    0   1       120
 19    58    1   2       140
 20    60    1   2       140
 21    67    0   0       106
 22    45    1   0       104
 23    63    0   2       135
 24    42    0   2       120
 25    61    0   0       145
 26    44    1   2       130
 27    58    0   1       136
 28    56    1   2       130
 29    55    0   0       180
 30    44    1   0       120
 ..   ...  ...  ..       ...
 530   60    0   0       150
 533   53    0   0       138
 536   50    0   2       120
 541   44    1   2       140
 549   68    1   2       118
 555   67    1   0       125
 566   50    0   0       110
 570   54    0   2       135
 580   46    1   1       101
 582   55    1   1       130
 594   64    1   0       145
 599   63    0   1       140
 606   66    1   0       112
 611   55    0   0       128
 616   43    1   0       115
 628   69    0   3       140
 629   65    1   3       138
 633   61    1   0       138
 643   65    1   0       120
 652   66    0   3       150
 691   55    0   1       135
 694   39    1   0       118
 708   60    0   2       120
 719   52    1   0       108
 720   64    1   2       140
 723   68    0   2       120
 733   44    0   2       108
 739   52    1   0       128
 843   59    1   3       160
 878   54    1   0       120

 [302 rows x 4 columns],
      trestbps  chol  fbs  restecg
 0         125   212    0        1
 1         140   203    1        0
 2         145   174    0        1
 3         148   203    0        1
 4         138   294    1        1
 5         100   248    0        0
 6         114   318    0        2
 7         160   289    0        0
 8         120   249    0        0
 9         122   286    0        0
 10        112   149    0        1
 11        132   341    1        0
 12        118   210    0        1
 13        140   298    0        1
 14        128   204    1        1
 16        140   308    0        0
 17        124   266    0        0
 18        120   244    0        1
 19        140   211    1        0
 20        140   185    0        0
 21        106   223    0        1
 22        104   208    0        0
 23        135   252    0        0
 24        120   209    0        1
 25        145   307    0        0
 26        130   233    0        1
 27        136   319    1        0
 28        130   256    1        0
 29        180   327    0        2
 30        120   169    0        1
 ..        ...   ...  ...      ...
 530       150   258    0        0
 533       138   234    0        0
 536       120   219    0        1
 541       140   235    0        0
 549       118   277    0        1
 555       125   254    1        1
 566       110   254    0        0
 570       135   304    1        1
 580       101   197    1        1
 582       130   262    0        1
 594       145   212    0        0
 599       140   195    0        1
 606       112   212    0        0
 611       128   205    0        2
 616       115   303    0        1
 628       140   239    0        1
 629       138   282    1        0
 633       138   166    0        0
 643       120   177    0        1
 652       150   226    0        1
 691       135   250    0        0
 694       118   219    0        1
 708       120   178    1        1
 719       108   233    1        1
 720       140   335    0        1
 723       120   211    0        0
 733       108   141    0        1
 739       128   255    0        1
 843       160   273    0        0
 878       120   188    0        1

 [302 rows x 4 columns])

In [33]:
data = pd.merge(df1,df2,on='trestbps',how='inner')
data.head()

   age  sex  cp  trestbps  chol  fbs  restecg
0   52    1   0       125   212    0        1
1   52    1   0       125   213    0        0
2   52    1   0       125   249    1        0
3   52    1   0       125   300    0        0
4   52    1   0       125   304    0        0

In [34]:
#Transformation
heart = heart.astype(str)

In [36]:
encoder = LabelEncoder()
for col in heart.select_dtypes(include=['object']):
    heart[col] = encoder.fit_transform(heart[col])

In [37]:
heart.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,18,1,0,17,43,0,1,60,0,10,2,2,3,0
1,19,1,0,27,34,1,0,47,1,29,0,0,3,0
2,36,1,0,30,12,0,1,18,1,25,0,0,3,0
3,27,1,0,32,34,0,1,53,0,0,2,1,3,0
4,28,0,0,26,116,1,1,2,0,18,1,3,2,0

In [38]:
heart.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [39]:
#model building

x = heart.drop(columns=['age'])
y = heart['cp']
y = y.round().astype(int)

In [40]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [41]:
model = RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [42]:
y_pred = model.predict(x_test)
y_pred

array([1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 0, 0, 2, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       3, 2, 0, 0, 2, 2, 0, 0, 1, 1, 1, 0, 1, 2, 0, 2, 0, 0, 0, 0, 0, 3,
       0, 0, 1, 0, 3, 2, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0], dtype=int32)

In [43]:
#accuracy
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

0.9508196721311475